### PR TITLE
fix sprockets engine registering for older sprocket-rails versions

### PR DESCRIPTION
**Pull request by fatbeard2**
fixes https://github.com/zweilove/css_splitter/issues/67

### CODE REVIEW

**Comment by jhilden** [comment]
thanks @fatbeard2

**Comment by hlcfan** [comment]
@jhilden Could you please bump the version and release to RubyGems? The version `0.4.4` I installed from RubyGems stale.

**Comment by jhilden** [comment]
just released `0.4.5`  thanks for the reminder

**Comment by hlcfan** [comment]
👍 Thank you!

**Pull request merged**
