### PR TITLE
Fix regex comparison for media queries

### PR DESCRIPTION
**Pull request by ernestoacevedo**
Hi, I wanna let you know that the gem wasn't working when there was a whitespace character before the @media rule so I change it.

### CODE REVIEW

**Comment by willbutler** [comment]
We were having the same issue. Thanks @ernestoacevedo!

**Comment by jhilden** [comment]
Thanks a lot for the fix @ernestoacevedo   I'm happy to merge it, but it would be awesome if you could add a failing test case for your bugfix.  The information provided by @cbeckr here (https://github.com/zweilove/css_splitter/issues/53#issuecomment-156831674) might be helpful to you.

**Comment by danielhusar** [comment]
+1

**Comment by gareth** [comment]
@jhilden :white_check_mark:

**Comment by jhilden** [comment]
thanks @gareth

**Comment by jhilden** [comment]
I released version `0.4.3` that includes this bugfix.

**Pull request merged**
